### ISSUE TITLE
partitions.json for batocera has wrong info for all versions plus adding new RPI4 build

### ISSUE THREAD

**Issue by nuwonda** [procount/pinn-os#8]
a couple of lines need updating in the batocera partitions and os json file.

partitions.json

     "label":                     "BATOCERA",
it's not RECALBOX

      "partition_size_nominal":    3096,
1.2GB is not enough space, users will not be able to update batocera. 3GB is minimum.

      "uncompressed_tarball_size": 1602,
310 is not the correct value. 5.26 is 1602

os.json
url for batocera changed to batocera.org (https://batocera-linux.xorhub.com/" is no longer valid)
rpi4 hex revisions added
entry for beta and stable possible
password changed to mirror batocera default password
download size changed to fit 5.26 size

{
    "name": "batocera_RPi4",
    "version": "5.26",
    "release_date": "2020-04-15",
    "description": "batocera.linux, the open source retro gaming console",
    "url": "https://batocera.org/",
    "group": "Games",
    "username": "root",
    "password": "linux",
    "supports_usb_boot": true,
    "supports_usb_root": true,
    "supports_backup": true,
    "download_size": 822813660,
    "supported_hex_revisions": "3111,3112",
    "supported_models": [
        "Pi 4 Model B",
        "Pi 4 Model B Rev 1.1"
    ]
}

for the os list json here's the changes required to add RPI4 beta and stable builds:
beta:

            "tarballs": [
                "https://batocera.org/upgrades/rpi4/beta/last/boot.tar.xz"
            ],

stable (not available yet)
           "tarballs": [
                "https://batocera.org/upgrades/rpi4/stable/last/boot.tar.xz"
            ],

I created my own jsons and install went fine, this is just on case you want to update the PINN entries here.

**Comment by procount** [comment]
Ping @matthuisman

**Comment by matthuisman** [comment]
this is the problem if OS's don't have their own NOOBS files but do have the correct tarballs. 
They can get "out of sync". eg. All the batocera issues were correct at the time of creating the files.

@procount 
What would be a good solution for this?
Always host the tarballs ourselves?
So we always need to manually allow updates?
That sounds annoying. haha

**Comment by matthuisman** [comment]
@nuwonda
Want to do a pull request with the fixes to my git?

**Comment by nuwonda** [comment]
@matthuisman sure can do. want me to add rpi4 as well?

**Comment by matthuisman** [comment]
Sure, just call it batocera_RPi4 please

**Comment by procount** [comment]
> What would be a good solution for this?
Always host the tarballs ourselves?
So we always need to manually do updates?
That sounds annoying. haha

There isn't a good solution.
That's why I mostly host them myself on sourceforge.
It's a pita. And why they get a bit out of date sometimes.
I think the only one I have that is like that is Arch, so I have to update the meta files every once in a while to keep them in sync.

> Also, this looks interesting:
> https://downloads.raspberrypi.org/os_list_imagingutility.json

Yes. Have you not seen this post on the best way to install PINN:
https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=142574&p=1644231#p1638508

**Comment by nuwonda** [comment]
i did a push with the changes. the only thing i didnt update is rpi1 and 2 bato folders as I dont download those so I dont have the current sizes. I updates the os lists for all rpi models though to have 3GB nominal partition size, cause it needs it to be able to update. once rpi4 builds are stable, can change the tarball to point to the stable dir. cheers!

**Comment by buvinghausen** [comment]
Sorry to do a necro bump but I always like to read previous issues before opening a new one if I can find a common theme and now that the pi5 is here and Batocera supports it I figured this was the place to ask.

So currently I can install Batocera 39 beta via the testing channel on my RPI5 and everything works as expected except the update process blows up stating the /boot partition is too small to download the update (It's 500mb and the download is 2gb alone)

[John has a video of the issue here](https://youtu.be/-eICl_RqdAE?t=600)

That's how I landed here...

@procount I actually found the info for [RPI5 Batocera 41 over on Source Forge](https://sourceforge.net/projects/pinn/files/os/batocera_RPi5/) but since today is the day I started playing with pinn I'm not sure how to pivot over to using that.  Lastly if I do get over to SF instead of the main github repo will that setup the necessary 3gb boot partition so that my Batocera partition can become self servicing? I want to apply updates when I'm ready/want to straight from the batocera UI instead of waiting for it to cycle through the understandable pinn SDLC.

Thank you for your time and I'm thrilled at the utility you have made available!

**Comment by buvinghausen** [comment]
@procount ok thanks for the update I'll check back periodically but right now I don't want to invest a bunch of time in getting the 39 beta setup correctly only to potentially have to re-do a bunch of things.  For now I'll just keep using RetroPie on Ubuntu though I look forward to making the switch.
